### ISSUE TITLE
cis-dil-benchmark-1.6.3.2: undefined method `positive?' for #<RSpec::Matchers::DSL::Matcher cmp>

### ISSUE THREAD

**Issue by benjamin-kuhar** [dev-sec/cis-dil-benchmark#105]
**Describe the bug**
Over the weekend, our nightly image builds started failing with the following error for cis-dil-benchmark-1.6.3.2:

```
undefined method `positive?' for #<RSpec::Matchers::DSL::Matcher cmp>"
```

**Expected behavior**
The test to run successfully and not throw an undefiend method error.

**Actual behavior**

```paste below
cis-dil-benchmark.cis-dil-benchmark-1.6.3.2

Command: `apparmor_status --profiled` stdout

{
  "message": "undefined method `positive?' for #<RSpec::Matchers::DSL::Matcher cmp>"
}
```

**Example code**

```paste below

```

**OS / Environment**

- Ubuntu 20.04
- Ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu] <-- This is the version provided from `apt`

**Inspec Version**

```paste below
4.22.8
```

**Baseline Version**

```paste below
master
```

**Additional context**
This started failing 3 days ago. Looks related to the apparmor test changes from https://github.com/dev-sec/cis-dil-benchmark/pull/104 in `controls/1_6_mandatory_access_control.rb`

**Comment by schurzi** [comment]
thank you for reporting this. It is now fixed in 0.4.10
