### ISSUE TITLE
Missing release for 0.4.12?

### ISSUE THREAD

**Issue by jrbeilke** [dev-sec/cis-dil-benchmark#123]
**Describe the bug**
The changelog mentions an [0.4.12](https://github.com/dev-sec/cis-dil-benchmark/tree/0.4.12) release/tag but I can't seem to find the tag in the github repo:
https://github.com/dev-sec/cis-dil-benchmark/blob/master/CHANGELOG.md

```
[0.4.12](https://github.com/dev-sec/cis-dil-benchmark/tree/0.4.12) (2022-03-18)
[Full Changelog](https://github.com/dev-sec/cis-dil-benchmark/compare/0.4.11...0.4.12)

Closed issues:

/var/log/btmp should be included in group_write_excepts for CIS 4.2.3 https://github.com/dev-sec/cis-dil-benchmark/issues/112
Merged pull requests:

Change linting to Cookstyle https://github.com/dev-sec/cis-dil-benchmark/pull/120 ([schurzi](https://github.com/schurzi))
cis-dil-benchmark-5.3.4 should match spaces better https://github.com/dev-sec/cis-dil-benchmark/pull/119 ([fargburger](https://github.com/fargburger))
(4.2.3) Add group write exemption for btmp https://github.com/dev-sec/cis-dil-benchmark/pull/116 ([bendres97](https://github.com/bendres97))
```

**Expected behavior**
Expecting an 0.4.12 tag and/or release to be available since it's mentioned in the changelog on `master`

**Actual behavior**
According to https://github.com/dev-sec/cis-dil-benchmark/tags the latest tag available is 0.4.11

**OS / Environment**
N/A

**Inspec Version**
N/A

**Baseline Version**
N/A

**Additional context**
Is there a versioning and/or release policy for this repo?  Would be nice to have something documented (ie. in the README) regarding release process and stable/supported version(s)

**Comment by micheelengronne** [comment]
Sorry, the draft for this release was not published. It is done.
