### ISSUE TITLE
Add support for arm64 architectures

### ISSUE THREAD

**Issue by spencer-cdw** [dev-sec/cis-dil-benchmark#130]
There are several controls that assume the cpu architecture is x86_64

e.g. cis-dil-benchmar-4.1.5

https://github.com/dev-sec/cis-dil-benchmark/blob/c060a8c70189ce389aa4a0a473344a6fdbbd3665/controls/4_1_configure_system_accounting_auditd.rb#L146-L157

Add support for architectures other than x86

Related: https://github.com/dev-sec/cis-dil-benchmark/pull/131

```
  if command('uname -m').stdout.strip == 'x86_64'
     #do stuff
  elsif command('uname -m').stdout.strip == 'i386'
     #do stuff
  else
    raise "unsupported architecture"
  end
```
e.g.

OSX: 
```
uname -m
arm64
```

Ubuntu
```
uname -m
aarch64
```

**Comment by deric4** [comment]
> There are other 64 bit architectures that are much more obscure. If you want they could be added here, however I think 99.9% of users will never use them, and limiting to just x86_64 and ARM will cover everyone
    https://github.com/dev-sec/cis-dil-benchmark/pull/133#issuecomment-1314035592

@spencer-cdw Is the conditional on `uname -m` needed? The audit procedure from the 22.04 benchmark uses the following **awk** regex:

```
/ -F *arch=b[2346]{2}/
```

Reading the `man 7 audit.rules`, it would seem that rules specifying both 32 and 64 bit architectures is not only valid, but recommended on bi-arch systems:

>  When you specify a syscall name, auditctl will look up the name and get its syscall number. This leads to some problems on bi-arch machines. The 32 and 64 bit syscall numbers sometimes, but not always, line up. So, to solve this problem, you would generally need to break the rule into 2 with one specifying -F arch=b32 and the other specifying -F arch=b64.
    https://man.archlinux.org/man/audit.rules.7.en#System_Call

ref: https://stackoverflow.com/a/45125525/4526019

**Comment by spencer-cdw** [comment]
>Is the conditional on uname -m needed?

For 64 bit systems, the inspec profile should include both 32 bit and 64 bit rules https://security.stackexchange.com/a/242462

```
-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change
-a always,exit -F arch=b64 -S clock_settime -k time-change
```

For 32 bit systems, my understanding is that it should only include the 32 bit. 

```
-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change
```

My understanding is that inspec is currently working properly for 32 bit and 64 bit systems (as long as they are x86 architecture). See the discussion in this [previously closed issue](https://github.com/dev-sec/cis-dil-benchmark/pull/131). 

That is why the 32bit line is _always_ set, but the 64 bit line is wrapped in a conditional to only apply to 64 bit systems.

**Comment by schurzi** [comment]
While discussing this with @rndmh3ro we also considered dropping the architecture check and generally assume we are on 64 bit systems. That might be a correct choice in 90+% of all cases, but it would also be a breaking change. So we are happy with extending the conditions in this benchmark.
