### ISSUE TITLE
Wrong modinfo option

### ISSUE THREAD

**Issue by ddepaoli3** [dev-sec/cis-dil-benchmark#4]
In file [libraries/linux_module.rb#L62-L64](https://github.com/dev-sec/cis-dil-benchmark/blob/master/libraries/linux_module.rb#L62-L64) the option _-v_ in [modinfo command](https://linux.die.net/man/8/modinfo) doesn't exist and the output of command method returns always with _nil_.
What do you want to test with _command_ method?

**Comment by rarenerd** [comment]
Resolved by https://github.com/dev-sec/cis-dil-benchmark/pull/10.
