### ISSUE TITLE
How much divergence from CIS DIL Benchmark document is accepted?

### ISSUE THREAD

**Issue by timstoop** [dev-sec/cis-dil-benchmark#43]
Hi,

I was wondering how much divergence from the document is accepted. Specifically, I'm working on a test for CIS DIL Benchmark 1.3.2 (Ensure filesystem integrity is regularly checked, aka is AIDE running regularly?) and on Debian Stretch, the proposed check will not work. Debian's AIDE comes with pretty elaborate cronjob scripts, which use values from /etc/default/aide to determine whether it should run or not. I'd like to add a test to see if those values are set correctly. However, this is entirely not described in the CIS DIL Benchmark documentation (at least not in the version I have), but it does keep with the intention of the document. Will such a PR be accepted or do you prefer to keep adhering to the document as much as possible?

**Comment by rarenerd** [comment]
The check boils down to "make sure AIDE is scheduled on the system", so anything you add to confirm that is OK by me. I'd prefer not to enforce any specific configuration of AIDE as that isn't enforced by the Benchmark either.

So if you have something that makes the check pass on Stretch that would be a very welcome PR.

The basic idea is to not be more strict than the actual benchmark in this profile. Where people want to do that they can include this benchmark in their own and just override the specific things they want.

**Comment by chris-rock** [comment]
I would also prefer to have a specific inspec aide baseline if required
