### ISSUE TITLE
Why are you using custom linux_module instead of the Inspec built in kernel_module?

### ISSUE THREAD

**Issue by itoperatorguy** [dev-sec/cis-dil-benchmark#48]
Hi,

Is there any specific reason why are you using your custom linux_module.rb instead of the kernel_module? Or it was not available back then? Do you have any plan to change it to the built in function?

Or if I send a pull request with the modification will you accept it?

**Comment by chris-rock** [comment]
I agree, we should switch to the official inspec `kernel_module` resource. A PR would be very welcome.

**Comment by jrbeilke** [comment]
Was this resolved with #49 ?

**Comment by rarenerd** [comment]
Yes it was.
