### ISSUE TITLE
Tagging versions for release?

### ISSUE THREAD

**Issue by jrbeilke** [dev-sec/cis-dil-benchmark#51]
Any chance this repo could use git tagging for releases and increment the version number in inspec.yml to match?

Would be really helpful for including this profile as a remote dependency within another profile for local exceptions/overrides.

**Comment by chris-rock** [comment]
@jrbeilke version 0.2.0 is released now https://github.com/dev-sec/cis-dil-benchmark/tree/0.2.0

**Comment by jrbeilke** [comment]
Thanks for the quick turnaround! :thumbsup:
