### ISSUE TITLE
dil-benchmark-1.6.2.2: undefined method `positive?' for #<RSpec::Matchers::DSL::Matcher cmp>

### ISSUE THREAD

**Issue by benjamin-kuhar** [dev-sec/cis-dil-benchmark#72]
**Describe the bug**
As of a couple of days ago, our DIL benchmarks have had an `undefined method 'positive?'` Rspec failure for the 1.6.2.2 control examining `apparmor_status --profiled`.

**Expected behavior**
I would expect this test to successfully run and not throw Rspec failures

**Actual behavior**

```paste below
<testcase name="Command: `apparmor_status --profiled` stdout " classname="cis-dil-benchmark.cis-dil-benchmark-1.6.2.2" target="ssh://ubuntu@127.0.0.1:2200" time="0.000119002">
<failure message="undefined method `positive?' for #<RSpec::Matchers::DSL::Matcher cmp>"/>
</testcase>
```

**Example code**

```paste below
```

**OS / Environment**

OS: Ubuntu 18.04

**Inspec Version**

```paste below
3.9.0
```

**Baseline Version**

```paste below
master
```

**Additional context**

**Comment by chris-rock** [comment]
Lets reverse the .positive? addition from the last PR. https://github.com/dev-sec/cis-dil-benchmark/pull/70/files#diff-6a65989c72f0ff31c2b298aa95a97e8bR154 Which ruby version are you using?

**Comment by benjamin-kuhar** [comment]
2.5 installed via our Ubuntu 18.04 container's apt-get.  This could be updated though since Inspec is the only thing using Ruby for our benchmarking, if it would fix this issue.

Is there any documentation stating minimum Inspec / Ruby versions?

Thanks for everything you all do here!

**Comment by chris-rock** [comment]
@benjamin-kuhar Can you try #73?

**Comment by benjamin-kuhar** [comment]
Hi @chris-rock,

The tests completed successfully for me when running from that branch.

**Comment by chris-rock** [comment]
@benjamin-kuhar Thank you for testing
