### ISSUE TITLE
The version on README.md is old

### ISSUE THREAD

**Issue by cawamata** [dev-sec/cis-dil-benchmark#94]
### Issue
After #90 was merged, this profile supports `CIS Distribution Independent Linux Benchmark v2.0.0`
However, README.md shown `This profile implements the CIS Distribution Independent Linux 1.0.1 Benchmark.`

### Solution
Update by correct version info.

**Comment by micheelengronne** [comment]
Can you do a patch ? I will merge it.

**Comment by deric4** [comment]
@micheelengronne sorry bout that!
